### ISSUE TITLE
Diamond Gems can be used in MCMMO Repairs

### ISSUE THREAD

**Issue by Malvagio87** [Nunnery/MythicDrops#250]
Diamond Gems can be used in MCMMO Repairs, however, they can not be used to craft items.

**Comment by conetopia** [comment]
lol thats funny, I never thought of that.
in mythic drops, in the socketting.yml you could remove diamonds from the ID list
and add something else.

I doubt the Dev would take the time to make it so diamond gems are 264:1 - 264:2 ect
If possible, you should contact the mcmmo dev team and ask them to make it so that
mcmmo repair only can be used with materials like leather/gold/iron/diamonds that doesn't have a Lore or Meta ID

**Comment by adnurmal** [comment]
All of them can be renamed in an anvil and used regularly as well, which is why I changed all mine to wheat, golden carrots, and flint.

**Comment by Nunnery** [comment]
It's only something that can be done on mcMMO's side. I just checked the code on mcMMO's side to see why it wasn't working and they don't use actual ItemStacks from the inventory, instead using MaterialData based removal of items.
