### ISSUE TITLE
Items Not Dropping

### ISSUE THREAD

**Issue by dani7beth** [Nunnery/MythicDrops#253]
I'm having an issue on my server of the items not dropping when mobs are killed. I got them to spawn on the mobs finally but they are not dropping once killed. Here is what i have set up for the mobs to drop.
Under the tier.yml:
chanceToSpawnOnAMonster: 0.75
  chanceToDropOnMonsterDeath: 1.0
  chanceToBeIdentified: 0.75
(every tier for chanceToDropOnMonsterDeath is set to 1.0)

Under the config.yml:
drops:
  item-chance: 0.25
  socket-gem-chance: 0.1
  identity-tome-chance: 0.2
  custom-item-chance: 0.35
  unidentified-item-chance: 0.2

Under the creatureSpawning.yml:
spawnWithDropChance:
  CREEPER: 1.0
  SKELETON: 1.0
  SPIDER: 1.0
  GIANT: 1.0
  ZOMBIE: 1.0
  GHAST: 1.0
  PIG_ZOMBIE: 1.0
  ENDERMAN: 1.0
  CAVE_SPIDER: 1.0
  SILVERFISH: 1.0
  BLAZE: 1.0
  MAGMA_CUBE: 1.0
  ENDER_DRAGON: 1.0
  WITHER: 1.0
  WITCH: 1.0

I cannot figure out as to why they are not dropping items at all. They will spawn with the items in hand but they will not drop the items whenever you kill them.

**Comment by Formula350** [comment]
I can confirm this issue; however, it is rather odd in that it only affects Overworld (World) and not the Nether (probably not The End), or any of our MultiVerse worlds of which it works in both of those (one is Flatlands, the other is a Skylands using SkylandsPlus generator). I personally have experienced it happen on Zombies, but originally chalked up the missing items to the fact that I have "can mobs pick up drops" set to True, but this has been happening to a few people now in regards to Legendary items dropping off WitherBosses when no other mob is around to "pick it up" (perhaps the drop is somehow running before the mob's death routine has finished and the item is somehow being picked up but deleted?)

I theorized that was perhaps the case and had one of my admins confirm it, so I then took a look at the config file. I considered that perhaps it had something to do with the fact that "world" was the first in the list of those to allow it to work in, which just so happens that it's the only world they ARE having this issue in. So I decided to move one of the other worlds to the top, one that isn't really important to have even set at all, and then... 
! ! ! DISCLAIMER: I know you have stated to NOT reload the plugin while server is live, that "things" can happen, but as of yet if I have PlugMan "disable" MythicDrops before I save whatever config file I'm changing, and then use PlugMan to "restart" MD, no issues have yet to have happened. ! ! !
... then after I made that change and performed my routine (mentioned in the disclaimer), instructing my Admin to try to have another Legendary item drop off a WitherBoss, this is the error that was produced when one finally did:
```javascript

28.11 20:25:19 [Server] ERROR Could not pass event EntityDeathEvent to MythicDrops v4.0.2-58e181c
28.11 20:25:19 [Server] INFO org.bukkit.event.EventException
28.11 20:25:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:377) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:873) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityWither.damageEntity(EntityWither.java:434) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
28.11 20:25:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-twkd.jar:git-Spigot-fdc1440-53fac9f]
28.11 20:25:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
28.11 20:25:19 [Server] INFO Caused by: java.lang.NullPointerException
28.11 20:25:19 [Server] INFO at mkremins.mythicdrops.fanciful.FancyMessage.send(FancyMessage.java:779) ~[?:?]
28.11 20:25:19 [Server] INFO at mkremins.mythicdrops.fanciful.FancyMessage.send(FancyMessage.java:768) ~[?:?]
28.11 20:25:19 [Server] INFO at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.broadcastMessage(ItemSpawningListener.java:431) ~[?:?]
28.11 20:25:19 [Server] INFO at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.handleEntityDyingWithGive(ItemSpawningListener.java:399) ~[?:?]
28.11 20:25:19 [Server] INFO at com.tealcube.minecraft.bukkit.mythicdrops.spawning.ItemSpawningListener.onEntityDeath(ItemSpawningListener.java:283) ~[?:?]
28.11 20:25:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor2118.invoke(Unknown Source) ~[?:?]
28.11 20:25:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
28.11 20:25:19 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
28.11 20:25:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
28.11 20:25:19 [Server] INFO ... 22 more
```

Whether or not the issue goes away with World moved down the list and after a server restart, we shall see in a few hours when it is due for it's bi-daily restart. Otherwise we've just put out a Heads Up that it is best to grind for loot either in the Nether or on the other Wilderness world.

Any further details I can provide, let me know. Hopefully MD hasn't been "abandoned", though... so fingers crossed!
-Form

**Comment by blakkember** [comment]
Hello,

I am having this issue as well. The Mythic Drops plugin is not allowing any gems or tiered items to be dropped. All it drops is the customitems.yml and I cannot figure out how to get this changed so that it works with ALL items defined.

Let me know what information you might need in order to help me fix this. Thanks.

**Comment by Nunnery** [comment]
Life's been incredibly busy the past few weeks and so I haven't been able to give MythicDrops the attention it deserves. This should be changing shortly, as the fall semester is almost over. I'll be looking into this issue this evening and will report back with any information that I find.

**Comment by blakkember** [comment]
Awesome, great to hear. Appreciate it very much!!

On Thu, Dec 10, 2015 at 10:18 AM, Richard Harrah <notifications@github.com>
wrote:

> Life's been incredibly busy the past few weeks and so I haven't been able
> to give MythicDrops the attention it deserves. This should be changing
> shortly, as the fall semester is almost over. I'll be looking into this
> issue this evening and will report back with any information that I find.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nunnery/MythicDrops/issues/253#issuecomment-163707638>
> .
>



-- 
Cameron Paris // Studio Firebolt
*Graphic Designer & Animator*
*http://studiofirebolt.com/ <http://studiofirebolt.com/>*
